- name: Fetch join command from master
  hosts: masters
  become: yes
  tasks:
    - name: Get join command
      ansible.builtin.shell: kubeadm token create --print-join-command
      register: kubeadm_join_command

    - name: Set join command fact
      set_fact:
        join_command: "{{ kubeadm_join_command.stdout }}"

    - name: Propagate join command to worker nodes
      ansible.builtin.add_host:
        name: "{{ item }}"
        join_command: "{{ kubeadm_join_command.stdout }}"
      loop: "{{ groups['workers'] }}"

- name: Join worker nodes to Kubernetes cluster
  hosts: workers
  become: yes
  tasks:
    - name: Join node to cluster
      ansible.builtin.shell: "{{ join_command }}"

