- name: Deploy Hashicorp Vault Agent
  hosts: all
  become: yes
  
  tasks: 
    - name: Downlad and add Hashicorp GPG Key
      ansible.builtin.apt_key:
        url: https://apt.releases.hashicorp.com/gpg
        state: present
        keyring: /usr/share/keyrings/hashicorp-archive-keyring.gpg

    - name: Add Hashicorp Apt Repo
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
        filename: hashicorp
        state: present

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Hashicorp Vault
      ansible.builtin.apt:
        name: vault
        state: present
        
    - name: Create Agent Directory
      ansible.builtin.file:
        path: /etc/vault
        state: directory
        owner: 'vault'
        group: 'vault'
        mode: '0755'

    - name: Generate Agent HCL
      ansible.builtin.template:
        src: ../templates/vault-agent/vault-agent.hcl.j2
        dest: /etc/vault/vault-agent.hcl
        owner: 'vault'
        group: 'vault'
        mode: '0775'

    - name: Create Template Directory
      ansible.builtin.file:
        path: /etc/vault/templates
        state: directory
        owner: 'vault'
        group: 'vault'
        mode: '0755'

    - name: Copy Key Tpl File
      ansible.builtin.copy:
        src: ../templates/vault-agent/key.tpl
        dest: /etc/vault/templates/key.tpl
        owner: 'vault'
        group: 'vault'
        mode: '0775'

    - name: Copy Cert Tpl File
      ansible.builtin.copy:
        src: ../templates/vault-agent/cert.tpl
        dest: /etc/vault/templates/cert.tpl
        owner: 'vault'
        group: 'vault'
        mode: '0775'

    - name: Copy Vault Service File
      ansible.builtin.copy:
        src: ../templates/vault-agent/vault-agent.service
        dest: /etc/systemd/system/vault-agent.service

    - name: Create Vault PID File
      ansible.buiiltin.file:
        path: /var/lib/vault/vault-agent.pid
        owner: 'vault'
        group: 'vault'
        mode: '0775'

    # TODO Get Role ID and Secret ID for Vault and Start Service
