---
- name: Initialize master and worker nodes
  hosts: k8s
  become: true
  tasks:
    - name: Disable UFW Firewall
      ansible.builtin.service:
        name: ufw
        state: stopped
        enabled: false

    - name: Disable SWAP
      shell: |
        swapoff -a 

    - name: Disable SWAP in fstab
      ansible.builtin.lineinfile:
        path: /etc/fstab
        regexp: ^.*swap.*$
        line: '#\0'
        backrefs: true

    - name: Install Apt Dependencies
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
        state: present
        update_cache: yes

    - name: Create Keyring Directory
      ansible.builtin.file:
        path: /etc/apt/keyrings
        mode: '0755'
        state: directory

    - name: Check if Docker GPG keyring exists
      ansible.builtin.stat:
        path: /etc/apt/keyrings/docker.asc
      register: docker_keyring_stat

    - name: Add Docker GPG Key
      ansible.builtin.shell: |
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | \
        gpg --dearmor -o /etc/apt/keyrings/docker.asc
      when: not docker_keyring_stat.stat.exists

    - name: Add Docker Repository
      ansible.builtin.shell: |
        echo \
          "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
          $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
          tee /etc/apt/sources.list.d/docker.list > /dev/null
      when: not docker_keyring_stat.stat.exists

    - name: Check if Kubernetes GPG keyring exists
      ansible.builtin.stat:
        path: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
      register: kubernetes_keyring_stat

    - name: Add Kubernetes GPG Key
      ansible.builtin.shell: |
        curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key | \
        gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
      when: not kubernetes_keyring_stat.stat.exists

    - name: Add Kubernetes Repository
      ansible.builtin.shell: |
        echo "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /" | \
        tee /etc/apt/sources.list.d/kubernetes.list
      when: not kubernetes_keyring_stat.stat.exists

    - name: Install Packages
      ansible.builtin.apt:
        name:
          - containerd.io
          - kubeadm
          - kubelet
          - kubectl
        state: present
        update_cache: yes

    - name: Set kernel parameters
      ansible.builtin.copy:
        dest: /etc/sysctl.d/k8s.conf
        content: |
          net.bridge.bridge-nf-call-iptables = 1
          net.ipv4.ip_forward = 1
          net.bridge.bridge-nf-call-ip6tables = 1

    - name: Apply sysctl parameters
      ansible.builtin.shell: |
        sysctl --system

    - name: Start kubelet
      service:
        name: kubelet
        enabled: true
        state: started
