- name: Fix malformed entries in APT sources list
  hosts: all
  become: yes
  tasks:
    - name: Remove malformed entries
      ansible.builtin.lineinfile:
        path: /etc/apt/sources.list
        state: absent
        regexp: '^(?!deb|deb-src)'
